"use client";
import { useEffect, useRef, useState } from "react";
import { importDocument } from "../../lib/importers";
import { pdfExporter } from "../../lib/export/pdf-exporter";
import { bounds, normalizePoint } from "../../lib/annotations/geometry";
import type { Annotation, AnnotationType, Point } from "../../types/annotation";
const tools: AnnotationType[] = ["ink", "pencil", "marker", "calligraphy", "highlighter", "text", "line", "arrow", "rectangle", "ellipse", "cloud", "note"];
const id = () => crypto.randomUUID();
export function ViewerClient() { const canvas = useRef<HTMLCanvasElement>(null), overlay = useRef<SVGSVGElement>(null), [source, setSource] = useState<ArrayBuffer>(), [page, setPage] = useState(1), [pages, setPages] = useState(0), [pdf, setPdf] = useState<any>(), [tool, setTool] = useState<AnnotationType>("ink"), [annotations, setAnnotations] = useState<Annotation[]>([]), [history, setHistory] = useState<Annotation[][]>([]), [future, setFuture] = useState<Annotation[][]>([]), [draft, setDraft] = useState<Point[] | null>(null), [color, setColor] = useState("#2563eb"), [opacity, setOpacity] = useState(1), [width, setWidth] = useState(3), [presenting, setPresenting] = useState(false);
  const visible = annotations.filter(a => a.pageNumber === page);
  const commit = (next: Annotation[]) => { setHistory(h => [...h, annotations]); setAnnotations(next); setFuture([]); localStorage.setItem("maples-annotations", JSON.stringify(next)); };
  useEffect(() => { const saved = localStorage.getItem("maples-annotations"); if (saved) setAnnotations(JSON.parse(saved) as Annotation[]); }, []);
  useEffect(() => { if (!pdf || !canvas.current) return; let cancelled = false; (async () => { const p = await pdf.getPage(page), viewport = p.getViewport({ scale: 1.5 }), c = canvas.current!; c.width = viewport.width; c.height = viewport.height; c.style.aspectRatio = `${viewport.width}/${viewport.height}`; await p.render({ canvasContext: c.getContext("2d")!, viewport }).promise; if (!cancelled && overlay.current) { overlay.current.setAttribute("viewBox", `0 0 ${viewport.width} ${viewport.height}`); } })(); return () => { cancelled = true; }; }, [pdf, page]);
  const open = async (file: File) => { const imported = await importDocument(file); const pdfjs = await import("pdfjs-dist"); pdfjs.GlobalWorkerOptions.workerSrc = new URL("pdfjs-dist/build/pdf.worker.min.mjs", import.meta.url).toString(); const document = await pdfjs.getDocument({ data: imported.data.slice(0) }).promise; setSource(imported.data); setPdf(document); setPages(document.numPages); setPage(1); };
  const point = (event: React.PointerEvent): Point => { const r = overlay.current!.getBoundingClientRect(); return normalizePoint({ x: event.clientX - r.left, y: event.clientY - r.top }, { width: r.width, height: r.height }); };
  const finish = (event: React.PointerEvent) => { if (!draft || !overlay.current) return; const points = [...draft, point(event)], b = bounds(points); const content = tool === "text" || tool === "note" ? window.prompt("Enter annotation text") ?? "" : undefined; if ((tool === "text" || tool === "note") && !content) { setDraft(null); return; } const annotation: Annotation = { id: id(), documentId: "local", pageNumber: page, type: tool, ...b, rotation: 0, style: { color, opacity: tool === "highlighter" ? Math.min(opacity, .45) : opacity, strokeWidth: width, fontSize: 18 }, content, points: tool === "ink" || tool === "pencil" || tool === "marker" || tool === "calligraphy" || tool === "highlighter" ? points : undefined, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() }; commit([...annotations, annotation]); setDraft(null); };
  return <main className={presenting ? "viewer presenting" : "viewer"}><header><a href="/">MAPLES ACADEMY SMARTBOARD TOOL</a><label className="upload">Open PDF / PPT / PPTX<input type="file" hidden accept=".pdf,.ppt,.pptx" onChange={e => e.target.files?.[0] && open(e.target.files[0]).catch(err => alert(err.message))} /></label><button onClick={() => setPresenting(v => !v)}>{presenting ? "Exit presentation" : "Present"}</button></header>{pdf ? <><nav aria-label="Annotation tools">{tools.map(t => <button className={tool === t ? "active" : ""} key={t} onClick={() => setTool(t)}>{t}</button>)}<input aria-label="Colour" type="color" value={color} onChange={e => setColor(e.target.value)} /><input aria-label="Opacity" type="range" min="0.1" max="1" step="0.1" value={opacity} onChange={e => setOpacity(+e.target.value)} /><input aria-label="Stroke width" type="range" min="1" max="16" value={width} onChange={e => setWidth(+e.target.value)} /><button onClick={() => { if (history.length) { setFuture(f => [annotations, ...f]); setAnnotations(history.at(-1)!); setHistory(h => h.slice(0, -1)); } }}>Undo</button><button onClick={() => { if (future.length) { setHistory(h => [...h, annotations]); setAnnotations(future[0]); setFuture(f => f.slice(1)); } }}>Redo</button><button onClick={() => commit(annotations.filter(a => a.pageNumber !== page))}>Clear page</button><button onClick={async () => { if (!source) return; const blob = await pdfExporter.export(source, annotations); const a = document.createElement("a"); a.href = URL.createObjectURL(blob); a.download = "annotated-lesson.pdf"; a.click(); }}>Export PDF</button></nav><section className="stage"><button aria-label="Previous page" disabled={page === 1} onClick={() => setPage(p => p - 1)}>‹</button><div className="page"><canvas ref={canvas} /><svg ref={overlay} onPointerDown={e => { e.currentTarget.setPointerCapture(e.pointerId); setDraft([point(e)]); }} onPointerMove={e => draft && setDraft(d => d ? [...d, point(e)] : null)} onPointerUp={finish}>{visible.map(a => <AnnotationShape key={a.id} a={a} onDelete={() => commit(annotations.filter(x => x.id !== a.id))} />)}{draft && <polyline points={draft.map(p => `${p.x * 1000},${p.y * 1000}`).join(" ")} fill="none" stroke={color} strokeWidth={width} />}</svg></div><button aria-label="Next page" disabled={page === pages} onClick={() => setPage(p => p + 1)}>›</button></section><footer><input aria-label="Page number" type="number" min="1" max={pages} value={page} onChange={e => setPage(Math.max(1, Math.min(pages, +e.target.value)))} /> / {pages}</footer></> : <section className="empty"><h1>Start a lesson</h1><p>Open a PDF now, or a PPT/PPTX when a conversion service is configured.</p></section>}</main>; }
function AnnotationShape({ a, onDelete }: { a: Annotation; onDelete: () => void }) { const x = a.x * 1000, y = a.y * 1000, w = a.width * 1000, h = a.height * 1000, common = { stroke: a.style.color, strokeWidth: a.style.strokeWidth, opacity: a.style.opacity, onDoubleClick: onDelete }; if (a.type === "ink" || a.type === "pencil" || a.type === "marker" || a.type === "calligraphy" || a.type === "highlighter") return <polyline points={(a.points ?? []).map(p => `${p.x * 1000},${p.y * 1000}`).join(" ")} fill="none" {...common} />; if (a.type === "ellipse") return <ellipse cx={x + w / 2} cy={y + h / 2} rx={w / 2} ry={h / 2} fill="none" {...common} />; if (a.type === "text" || a.type === "note") return <text x={x} y={y + 20} fill={a.style.color} onDoubleClick={onDelete}>{a.content}</text>; return <rect x={x} y={y} width={w} height={h} fill="none" {...common} />; }
